_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: es
uuid: c8bc61b8-f17e-4b7a-b971-132f9d5a06ba
name: DrupalDemo
mail: correo@correocaliente.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: es
